baseURL = 'https://i4bree.github.io/'
languageCode = 'en-us'
title = "Bree's Digital Diary"
theme = "PaperMod"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true
publishDir = "docs"

[minify]
disableXML = true
minifyOutput = true

[taxonomies]
tag = "tags"

[params]
env = "production"
title = "Bryanna Downing"
description = "My digital diary"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Bryanna Downing"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  safari_pinned_tab = "/favicon-16x16.png"

  [params.label]
  text = "Bree's Digital Diary ðŸŒ±"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Bryanna Downing"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi, I'm Bryanna! ðŸŒ·"
  Content = "Welcome to my digital diary where I document my learnings as a Biomedical Engineer."

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/i4bree"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/bryanna-downing/"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "archive"
name = "archive"
url = "/archive/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 40

[markup.highlight]
noClasses = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]